name: GameStore Deploy

on:
  push:
    branches:
      - dev
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Prepare WordPress Zip
      run: |
        WP_LINK=$(cat wp-_version-control.cfg)
        wget -O "./wordpress.zip" $WP_LINK

    - name: Prepare plugins and theme zip
      run: zip -r wpcontent.zip plugins mu-plugins themes

    - name: Copy Zips to Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        source: "./wordpress.zip, ./wpcontent.zip"
        target: ${{ github.event_name == 'push' && 'public_html/dev_version' || 'public_html/prod_version' }}

    - name: Enable Maintenance Mode
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        source: ".maintenance"
        target: ${{ github.event_name == 'push' && 'public_html/dev_version' || 'public_html/prod_version' }}
        
    - name: Update WordPress Core
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          find "${{ github.event_name == 'push' && 'wordpress-dev/public_html/dev_version' || 'wordpress-dev/public_html/prod_version' }}" -type f -name "*.php" ! -name "wp-config.php" -delete
          rm -r "${{ github.event_name == 'push' && 'wordpress-dev/public_html/dev_version' || 'wordpress-dev/public_html/prod_version' }}/wp-admin/" "${{ github.event_name == 'push' && 'wordpress-dev/public_html/dev_version' || 'wordpress-dev/public_html/prod_version' }}/wp-includes/"
          unzip -o "${{ github.event_name == 'push' && 'wordpress-dev/public_html/dev_version' || 'wordpress-dev/public_html/live.geniuscourses.com' }}/wordpress.zip" -d "${{ github.event_name == 'push' && 'wordpress-dev/public_html/dev_version' || 'wordpress-dev/public_html/prod_version' }}/"
          mv "${{ github.event_name == 'push' && 'wordpress-dev/public_html/dev_version' || 'wordpress-dev/public_html/prod_version' }}/wordpress"/* "${{ github.event_name == 'push' && 'wordpress-dev/public_html/dev_version' || 'wordpress-dev/public_html/prod_version' }}/"
          rm -r "${{ github.event_name == 'push' && 'wordpress-dev/public_html/dev_version' || 'wordpress-dev/public_html/prod_version' }}/wordpress"    

    - name: Update Plugins and Theme
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          rm -rf "${{ github.event_name == 'push' && 'wordpress-dev/public_html/dev_version' || 'wordpress-dev/public_html/prod_version' }}/wp-content/plugins" "${{ github.event_name == 'push' && 'public_html/dev_version' || 'public_html/prod_version' }}/wp-content/mu-plugins" "${{ github.event_name == 'push' && 'public_html/dev_version' || 'public_html/prod_version' }}/wp-content/themes"
          unzip -o "${{ github.event_name == 'push' && 'wordpress-dev/public_html/dev_version' || 'wordpress-dev/public_html/prod_version' }}/wpcontent.zip" -d "${{ github.event_name == 'push' && 'public_html/dev_version' || 'public_html/prod_version' }}/wp-content/"      
          
    - name: Disable Maintenance Mode and Remove zips
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          rm -f "${{ github.event_name == 'push' && 'wordpress-dev/public_html/dev_version' || 'wordpress-dev/public_html/prod_version' }}/.maintenance"
          rm -f "${{ github.event_name == 'push' && 'wordpress-dev/public_html/dev_version' || 'wordpress-dev/public_html/prod_version' }}/wpcontent.zip"
          rm -f "${{ github.event_name == 'push' && 'wordpress-dev/public_html/dev_version' || 'wordpress-dev/public_html/prod_version' }}/wordpress.zip"